### ISSUE TITLE
error！hmac没考虑key长度大于64的情况

### ISSUE THREAD

**Issue by xmhwws** [mygityf/cipher#1]
偶然发现调用hmac_md5生成错误的值，对源码进行分析，发现没考虑key大于64的情况
![image](https://user-images.githubusercontent.com/42903751/134793085-09c50d1d-49bf-4b35-9f96-9ed145a00cb8.png)
![image](https://user-images.githubusercontent.com/42903751/134793015-885a9f81-cf33-431c-9981-596a4efc0b1b.png)

稍微看了下，似乎所有hmac都没有考虑key大于64的情况

**Comment by mygityf** [comment]
是没有考虑key大于64的case

**Comment by mygityf** [comment]
已修复。
fix done
